### ISSUE TITLE
Gamecrash for Everyone...

### ISSUE THREAD

**Issue by Kuroosh** [KWMSources/pedSyncer#5]
If a Player spawns/is near another player... everyone's pc crash... tested it with Heron, LargePeach & Solid_Snake

**Comment by KWMSources** [comment]
I don't understand the problem. What are you exactly doing and what happens when? Can you get me the exception in the client log if there is some?

**Comment by Kuroosh** [comment]
wäre am besten wenn du ts3 kommst : 

ts.venox-reallife.com ( wir 3 sind bereits hier :D )

**Comment by KWMSources** [comment]
Bin da.

**Comment by KWMSources** [comment]
For all: There is a problem at setting `player.model`. It seems that setting of the `player.model` leads to a client crash of other clients in range. Maybe it's an altv problem. The dumps was sended to vekktor.
